---
- name: Copy configuration
  template:
    src: "{{ item }}"
    dest: /etc/bind/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - ../templates/*.j2
  register: config

- name: Bind check config
  command: named-checkconf
  when: config.changed
  notify:
    - reload bind
